using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace WinFormsApp1
{
    public partial class frmPOStatusView : Form
    {
        private readonly DataAccessLayer _dal = new DataAccessLayer();
        private string _selectedPO = "";

        private static readonly string[] StatusOptions =
        {
            "All",
            "Created",
            "Pending PM / Dept Approval",
            "Pending MH Approval",
            "Pending Purchase Committee",
            "Pending OM Approval",
            "Pending GM Approval",
            "Ready to Generate",
            "PO Generated",
            "Sent to Vendor",
            "Partially Received",
            "Fully Received",
            "Under Review",
            "Closed",
            "Cancelled",
            "Deleted"
        };

        public frmPOStatusView()
        {
            InitializeComponent();
        }

        private void frmPOStatusView_Load(object sender, EventArgs e)
        {
            lblUser.Text = AppSession.DisplayLabel;
            cmbStatus.Items.Clear();
            cmbStatus.Items.AddRange(StatusOptions);
            cmbStatus.SelectedIndex = 0;
            dtpFrom.Value = DateTime.Today.AddMonths(-6);
            dtpTo.Value = DateTime.Today;
            chkDateFilter.Checked = false;
            dtpFrom.Enabled = false;
            dtpTo.Enabled = false;
            LoadStatusList();
        }

        private void chkDateFilter_CheckedChanged(object sender, EventArgs e)
        {
            dtpFrom.Enabled = chkDateFilter.Checked;
            dtpTo.Enabled = chkDateFilter.Checked;
        }

        private void btnSearch_Click(object sender, EventArgs e) => LoadStatusList();

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            txtPONumber.Clear();
            txtVendor.Clear();
            txtProject.Clear();
            cmbStatus.SelectedIndex = 0;
            chkDateFilter.Checked = false;
            LoadStatusList();
        }

        private void LoadStatusList()
        {
            string status = cmbStatus.SelectedItem?.ToString() ?? "All";
            DateTime? from = chkDateFilter.Checked ? dtpFrom.Value.Date : null;
            DateTime? to = chkDateFilter.Checked ? dtpTo.Value.Date : null;

            DataSet ds = _dal.fnPOStatusList(status, txtPONumber.Text, txtVendor.Text, txtProject.Text, from, to);
            DataTable dt = ds?.Tables.Count > 0 ? ds.Tables[0] : new DataTable();
            dgvPOList.DataSource = dt;
            FormatListGrid();
            ColorStatusRows();
            lblCount.Text = "POs: " + dt.Rows.Count;
            UpdateSummaryChips(dt);
            ClearDetail();
        }

        private void FormatListGrid()
        {
            dgvPOList.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvPOList.RowHeadersVisible = false;
            dgvPOList.AllowUserToAddRows = false;
            dgvPOList.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvPOList.MultiSelect = false;
            dgvPOList.ReadOnly = true;

            string[] hide =
            {
                "PMApproved", "MHApproved", "OMApproved", "POApproved",
                "PMApprovedDate", "MHApprovedDate", "FinalizedDate", "PCAuthoriseDate",
                "OMApprovedDate", "GMApprovedDate", "POSentVendorDate", "AuthoriedBy",
                "RejectReason", "FinalComment", "BOMProjects"
            };
            foreach (string col in hide)
            {
                if (dgvPOList.Columns.Contains(col))
                    dgvPOList.Columns[col].Visible = false;
            }

            SetHeader("PONumber", "PO Number");
            SetHeader("ProjectCode", "Project");
            SetHeader("ProjectDescription", "Project Name");
            SetHeader("VendorName", "Vendor");
            SetHeader("PreparedBy", "Prepared By");
            SetHeader("PreparedDate", "Prepared");
            SetHeader("DeliveryDate", "Delivery");
            SetHeader("TotalAmount", "Amount");
            SetHeader("RemainingQty", "Rem Qty");
            SetHeader("CurrentStatus", "Status");
            SetHeader("POGeneratedBy", "Generated By");
            SetHeader("POGeneratedDate", "Generated");
            SetHeader("PurchaseCommitee", "PC");
            SetHeader("GMName", "GM");
            SetHeader("OMName", "OM");
        }

        private void SetHeader(string col, string text)
        {
            if (dgvPOList.Columns.Contains(col))
                dgvPOList.Columns[col].HeaderText = text;
        }

        private void ColorStatusRows()
        {
            if (!dgvPOList.Columns.Contains("CurrentStatus"))
                return;

            foreach (DataGridViewRow row in dgvPOList.Rows)
            {
                string status = row.Cells["CurrentStatus"].Value?.ToString() ?? "";
                Color back = status switch
                {
                    "Cancelled" or "Deleted" => Color.FromArgb(255, 230, 230),
                    "Closed" => Color.FromArgb(230, 230, 230),
                    "Under Review" => Color.FromArgb(255, 245, 200),
                    "Fully Received" => Color.FromArgb(220, 245, 220),
                    "Partially Received" => Color.FromArgb(230, 245, 255),
                    "Ready to Generate" => Color.FromArgb(225, 240, 255),
                    "PO Generated" or "Sent to Vendor" => Color.FromArgb(235, 250, 235),
                    "Pending GM Approval" => Color.FromArgb(255, 235, 210),
                    _ when status.StartsWith("Pending", StringComparison.OrdinalIgnoreCase)
                        => Color.FromArgb(255, 248, 230),
                    _ => Color.White
                };
                row.DefaultCellStyle.BackColor = back;
            }
        }

        private void UpdateSummaryChips(DataTable dt)
        {
            flpSummary.Controls.Clear();
            var counts = new System.Collections.Generic.SortedDictionary<string, int>();
            foreach (DataRow row in dt.Rows)
            {
                string st = row["CurrentStatus"]?.ToString() ?? "Unknown";
                if (!counts.ContainsKey(st)) counts[st] = 0;
                counts[st]++;
            }

            foreach (var kv in counts)
            {
                var chip = new Label
                {
                    AutoSize = true,
                    Margin = new Padding(4),
                    Padding = new Padding(8, 4, 8, 4),
                    BackColor = Color.FromArgb(20, 55, 90),
                    ForeColor = Color.White,
                    Font = new Font("Segoe UI", 8.5F, FontStyle.Bold),
                    Text = kv.Key + ": " + kv.Value
                };
                flpSummary.Controls.Add(chip);
            }
        }

        private void dgvPOList_SelectionChanged(object sender, EventArgs e)
        {
            if (dgvPOList.CurrentRow == null || dgvPOList.CurrentRow.DataBoundItem is not DataRowView view)
            {
                ClearDetail();
                return;
            }

            DataRow row = view.Row;
            _selectedPO = row["PONumber"]?.ToString() ?? "";
            ShowDetail(row);
            LoadLinesAndTimeline(_selectedPO);
        }

        private void ShowDetail(DataRow row)
        {
            string status = row["CurrentStatus"]?.ToString() ?? "-";
            lblPO.Text = "PO: " + row["PONumber"];
            lblStatus.Text = status;
            lblStatus.ForeColor = StatusColor(status);
            lblProject.Text = "Project: " + row["ProjectCode"] + " — " + row["ProjectDescription"];
            lblVendor.Text = "Vendor: " + row["VendorCode"] + " — " + row["VendorName"];
            lblPrepared.Text = "Prepared: " + row["PreparedBy"] + " / " + row["PreparedDate"];
            lblAmount.Text = "Amount: " + Convert.ToDecimal(row["TotalAmount"] == DBNull.Value ? 0 : row["TotalAmount"]).ToString("N2")
                             + " " + (row["Currency"]?.ToString() ?? "");
            lblDelivery.Text = "Delivery: " + row["DeliveryDate"];
            lblFinal.Text = string.IsNullOrWhiteSpace(row["FinalStatus"]?.ToString())
                ? "Lifecycle: Active"
                : "Lifecycle: " + row["FinalStatus"] + " — " + row["FinalComment"];

            BuildPipeline(row);
        }

        private static Color StatusColor(string status) => status switch
        {
            "Cancelled" or "Deleted" => Color.Firebrick,
            "Closed" => Color.DimGray,
            "Under Review" => Color.DarkOrange,
            "Fully Received" => Color.ForestGreen,
            "Ready to Generate" or "PO Generated" or "Sent to Vendor" => Color.DarkGreen,
            _ when status.StartsWith("Pending", StringComparison.OrdinalIgnoreCase) => Color.Chocolate,
            _ => Color.FromArgb(20, 55, 90)
        };

        private void BuildPipeline(DataRow row)
        {
            flpPipeline.Controls.Clear();
            AddStep("Created", true, row["PreparedBy"]?.ToString(), row["PreparedDate"]?.ToString());
            AddStep("PM", IsFilled(row["PMName"]) || ToBool(row["PMApproved"]), row["PMName"]?.ToString(), row["PMApprovedDate"]?.ToString());
            AddStep("MH", IsFilled(row["MHName"]) || ToBool(row["MHApproved"]), row["MHName"]?.ToString(), row["MHApprovedDate"]?.ToString());
            AddStep("PC", IsFilled(row["PurchaseCommitee"]), row["PurchaseCommitee"]?.ToString(), row["PCAuthoriseDate"]?.ToString());
            AddStep("OM", IsFilled(row["OMName"]) || ToBool(row["OMApproved"]), row["OMName"]?.ToString(), row["OMApprovedDate"]?.ToString());
            AddStep("GM", IsFilled(row["GMName"]), row["GMName"]?.ToString(), row["GMApprovedDate"]?.ToString());
            AddStep("Approved", ToBool(row["POApproved"]), ToBool(row["POApproved"]) ? "Yes" : "No", null);
            AddStep("Generated", IsFilled(row["POGeneratedBy"]) && row["POGeneratedBy"]?.ToString() != "Deleted",
                row["POGeneratedBy"]?.ToString(), row["POGeneratedDate"]?.ToString());
            AddStep("Vendor", IsFilled(row["POSenttoVendorBy"]), row["POSenttoVendorBy"]?.ToString(), row["POSentVendorDate"]?.ToString());

            decimal rem = Convert.ToDecimal(row["RemainingQty"] == DBNull.Value ? 0 : row["RemainingQty"]);
            decimal tot = Convert.ToDecimal(row["TotalQty"] == DBNull.Value ? 0 : row["TotalQty"]);
            bool received = IsFilled(row["POGeneratedBy"]) && rem < tot;
            AddStep("Receipt", received, rem <= 0 && tot > 0 ? "Full" : (received ? "Partial" : "Pending"), null);
        }

        private void AddStep(string title, bool done, string who, string when)
        {
            var panel = new Panel
            {
                Width = 108,
                Height = 72,
                Margin = new Padding(4),
                BackColor = done ? Color.FromArgb(40, 120, 90) : Color.FromArgb(210, 215, 220)
            };
            var lblTitle = new Label
            {
                Text = title,
                ForeColor = done ? Color.White : Color.FromArgb(70, 70, 70),
                Font = new Font("Segoe UI Semibold", 8.5F, FontStyle.Bold),
                Location = new Point(6, 6),
                AutoSize = true
            };
            var lblWho = new Label
            {
                Text = string.IsNullOrWhiteSpace(who) || who == "--" ? (done ? "Done" : "—") : who,
                ForeColor = done ? Color.FromArgb(220, 240, 230) : Color.FromArgb(100, 100, 100),
                Font = new Font("Segoe UI", 7.5F),
                Location = new Point(6, 28),
                MaximumSize = new Size(96, 40),
                AutoSize = true
            };
            panel.Controls.Add(lblTitle);
            panel.Controls.Add(lblWho);
            if (!string.IsNullOrWhiteSpace(when) && when != "--")
            {
                panel.Controls.Add(new Label
                {
                    Text = when.Length > 16 ? when.Substring(0, 16) : when,
                    ForeColor = done ? Color.FromArgb(200, 230, 210) : Color.Gray,
                    Font = new Font("Segoe UI", 7F),
                    Location = new Point(6, 52),
                    AutoSize = true
                });
            }
            flpPipeline.Controls.Add(panel);
        }

        private static bool IsFilled(object value)
        {
            if (value == null || value == DBNull.Value) return false;
            string s = value.ToString()?.Trim() ?? "";
            return s.Length > 0 && s != "--";
        }

        private static bool ToBool(object value)
        {
            if (value == null || value == DBNull.Value) return false;
            if (value is bool b) return b;
            if (int.TryParse(value.ToString(), out int i)) return i != 0;
            return false;
        }

        private void LoadLinesAndTimeline(string poNumber)
        {
            DataSet lines = _dal.fnPOStatusLines(poNumber);
            dgvLines.DataSource = lines?.Tables.Count > 0 ? lines.Tables[0] : null;
            dgvLines.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvLines.RowHeadersVisible = false;
            dgvLines.ReadOnly = true;
            dgvLines.AllowUserToAddRows = false;

            DataSet remarks = _dal.PORemarksHistory(1, poNumber);
            DataTable timeline = BuildTimelineTable(remarks?.Tables.Count > 0 ? remarks.Tables[0] : null);
            dgvTimeline.DataSource = timeline;
            dgvTimeline.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvTimeline.RowHeadersVisible = false;
            dgvTimeline.ReadOnly = true;
            dgvTimeline.AllowUserToAddRows = false;
        }

        private static DataTable BuildTimelineTable(DataTable raw)
        {
            DataTable t = new DataTable();
            t.Columns.Add("Stage", typeof(string));
            t.Columns.Add("User", typeof(string));
            t.Columns.Add("Date", typeof(string));
            t.Columns.Add("Remarks", typeof(string));

            string[] stages =
            {
                "Prepared", "PM Approval", "Finalized / MH", "Purchase Committee",
                "OM Approval", "Finance", "GM Approval", "PO Update Request"
            };

            if (raw == null || raw.Rows.Count == 0)
                return t;

            for (int i = 0; i < raw.Rows.Count && i < stages.Length; i++)
            {
                DataRow r = raw.Rows[i];
                string user = r[0]?.ToString() ?? "";
                if (string.IsNullOrWhiteSpace(user) || user == "--")
                    continue;
                t.Rows.Add(stages[i], user, r[1]?.ToString() ?? "", r[2]?.ToString() ?? "");
            }
            return t;
        }

        private void ClearDetail()
        {
            _selectedPO = "";
            lblPO.Text = "PO: —";
            lblStatus.Text = "Select a PO";
            lblStatus.ForeColor = Color.FromArgb(20, 55, 90);
            lblProject.Text = "Project: —";
            lblVendor.Text = "Vendor: —";
            lblPrepared.Text = "Prepared: —";
            lblAmount.Text = "Amount: —";
            lblDelivery.Text = "Delivery: —";
            lblFinal.Text = "Lifecycle: —";
            flpPipeline.Controls.Clear();
            dgvLines.DataSource = null;
            dgvTimeline.DataSource = null;
        }

        private void btnClose_Click(object sender, EventArgs e) => Close();
    }
}
