
using System;

namespace WinFormsApp1
{
    /// <summary>
    /// PR to PO Conversion Model
    /// Maps PurchaseRequest data to existing PurchaseOrder table
    /// </summary>
    public class PRtoPOModel
    {
        // Primary Key (auto-generated by PO table)
        public int ID { get; set; }

        // === PR Reference ===
        public string DBOMNo { get; set; }          // Maps to PR.PRNumber
        public int PRID { get; set; }
        public int DetailID { get; set; }

        // === Project Info ===
        public string ProjectCode { get; set; }
        public string BOMProjectList { get; set; }  // For clubbed PRs: comma-separated projects

        // === Vendor Info ===
        public string VendorCode { get; set; }
        public string VendorName { get; set; }

        // === Item Details (from PR Detail) ===
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string Specification { get; set; }
        public string Make { get; set; }
        public string MfgPartNo { get; set; }

        // === Quantities ===
        public float RequariedQty { get; set; }     // PR Quantity
        public string UOM { get; set; }
        public float UnitPrice { get; set; }          // PR UnitCost
        public float Amount { get; set; }             // PR TotalCost
        public float RemainingQty { get; set; }       // Same as RequariedQty initially
        public float BOMQty { get; set; }             // Original BOM quantity

        // === PO Status & Approval ===
        public string PreparedBy { get; set; }
        public string AuthoriedBy { get; set; }
        public string POGeneratedBy { get; set; }
        public string POGeneratedDate { get; set; }
        public string POPreparedDate { get; set; }
        public string PODeliveryDate { get; set; }
        public string ProjectStatus { get; set; }
        public bool POApproved { get; set; }
        public bool WithoutBOM { get; set; }

        // === GST (can be calculated later in PO approval) ===
        public float IGSTRate { get; set; }
        public float IGSTAmount { get; set; }
        public float SGSTRate { get; set; }
        public float SGSTAmount { get; set; }
        public float CGSTRate { get; set; }
        public float CGSTAmount { get; set; }

        // === Discount ===
        public float DiscRate { get; set; }
        public float DiscAmount { get; set; }

        // === Currency ===
        public string Currency { get; set; }
        public float FXRate { get; set; }

        // === Remarks ===
        public string Remarks { get; set; }
        public string RejectReason { get; set; }

        // === Approval Chain (filled during PO approval workflow) ===
        public string PMName { get; set; }
        public bool PMApproved { get; set; }
        public string PMApprovedDate { get; set; }
        public string MHName { get; set; }
        public bool MHApproved { get; set; }
        public string MHApprovedDate { get; set; }
        public string GMName { get; set; }
        public string GMApprovedDate { get; set; }
        public bool GMCostApproved { get; set; }
        public string PurchaseCommitee { get; set; }
        public string PCRemarks { get; set; }
        public string PCAuthoriseDate { get; set; }
        public string FinanceApproverName { get; set; }
        public string FinanceApprovedDate { get; set; }
        public string FinanceRemarks { get; set; }
        public string FinalizedBy { get; set; }
        public string FinalizedDate { get; set; }
        public string FinalizedRemarks { get; set; }
        public string OMName { get; set; }
        public bool OMApproved { get; set; }
        public string OMApprovedDate { get; set; }
        public string OMRemarks { get; set; }
        public string FinalStatus { get; set; }
        public string FinalComment { get; set; }

        // === Cost Comparison ===
        public float StandardCost { get; set; }
        public float DiffinPer { get; set; }
        public float DiffinRs { get; set; }
        public float LatestPurchasePrice { get; set; }

        // === Cancellation ===
        public string CancelledBy { get; set; }
        public DateTime? CancelledDate { get; set; }
        public string ClosedBy { get; set; }
        public DateTime? ClosedDate { get; set; }

        // === PO Update ===
        public bool POUpdate { get; set; }
        public string POUpdateRemarks { get; set; }
        public string POUpdateRequestBy { get; set; }
        public string POUpdatedBy { get; set; }
        public string FinalRemarks { get; set; }
        public string POSenttoVendorBy { get; set; }
        public string POSentVendorDate { get; set; }
        public string POUptoDate { get; set; }
    }
}